export const focusOptions = [
  {
    id: "grammar",
    label: "Grammaire",
    description: "Comprendre un moule puis le transformer",
    primitives: ["EX-EXPOSE-01", "EX-RECALL-02", "EX-TRANSFORM-01"],
    target: "grammar:review",
    modalities: ["reading", "writing"],
  },
  {
    id: "conjugation",
    label: "Conjugaison",
    description: "Construire et rappeler des formes verbales",
    primitives: ["EX-EXPOSE-01", "EX-RECALL-06", "EX-TRANSFORM-01"],
    target: "morphology:conjugation",
    modalities: ["reading", "writing"],
  },
  {
    id: "vocabulary",
    label: "Vocabulaire",
    description: "Reconnaissance, rappel et réemploi",
    primitives: ["EX-DISC-02", "EX-RECALL-01", "EX-RECALL-03"],
    target: "lexicon:due",
    modalities: ["reading", "writing"],
  },
  {
    id: "spelling",
    label: "Orthographe",
    description: "Texte à trous, dictée et réparation",
    primitives: ["EX-RECALL-02", "EX-RECALL-04", "EX-REPAIR-01"],
    target: "orthography:review",
    modalities: ["listening", "writing"],
  },
  {
    id: "listening",
    label: "Écoute",
    description: "Comprendre, transcrire et répéter",
    primitives: ["EX-COMP-02", "EX-RECALL-05", "EX-ORAL-01"],
    target: "communication:listening",
    modalities: ["listening", "speaking"],
  },
  {
    id: "pronunciation",
    label: "Prononciation",
    description: "Repérage sonore et répétition guidée",
    primitives: ["EX-EXPOSE-01", "EX-DISC-06", "EX-ORAL-01"],
    target: "pronunciation:review",
    modalities: ["listening", "speaking"],
  },
  {
    id: "translation",
    label: "Traduction",
    description: "Version, thème et correction idiomatique",
    primitives: ["EX-COMP-03", "EX-REPAIR-01", "EX-PROD-01"],
    target: "communication:translation",
    modalities: ["reading", "writing"],
  },
  {
    id: "writing",
    label: "Écriture",
    description: "Production guidée puis production libre",
    primitives: ["EX-RECALL-07", "EX-PROD-01", "EX-PROD-03"],
    target: "communication:writing",
    modalities: ["reading", "writing"],
  },
] as const;
